# Initial Setup

In [45]:
# Import libraries and functions
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression

In [46]:
# Import dataset
df = pd.read_csv('../data_synthetic/dataset.csv')
# View contents
df

,applicant_id,income,loan_amount,term,credit_history,default
0,1a7b9fae-e0da-4e16-976a-b5e8b28646ff,14662,657144,30,1,0
1,7d8ce617-2895-4d5e-b155-7a26a2ae37f7,17636,226200,54,1,1
2,79ef5c77-ca8b-4170-bdf4-1047bc9e08e3,17847,323619,24,0,0
3,f456cdf0-15fa-4c2b-bcb4-d28f415a2322,20556,619547,42,1,1
4,7bfa003a-6716-4a2b-9e65-d3aa21841639,17510,332159,60,1,1
...,...,...,...,...,...,...
1995,42670a17-d130-45d7-a9dc-70721724341d,29378,852745,18,0,1
1996,3a330e2f-e62c-4b1f-9cdc-460f10e09ef6,23980,968074,6,0,1
1997,7ac45afa-0952-4b4c-964b-dc95dae02194,12758,796408,36,1,0
1998,b3a7c7ce-7e35-4955-b56b-b5e2304c0e0c,23237,859989,54,1,1
1999,cd52dbbd-b953-4a9d-b6c4-1e01a8787747,6608,544618,42,0,1

# Data preparation

In [47]:
# See row and column count
df.shape

(2000, 6)

In [48]:
# We will not be using the ID primary key to train the model, so it is dropped
df = df.drop('applicant_id', axis=1)
df.shape

(2000, 5)

In [49]:
# Check for missing values (Just in case, but there should be none)
df.isna().sum()

income            0
loan_amount       0
term              0
credit_history    0
default           0
dtype: int64

In [50]:
# Count the number of defaulted loans (1) and good loans (0)
df['default'].value_counts()

default
1    1309
0     691
Name: count, dtype: int64

In [51]:
# Summarize the data by default
df.groupby('default').mean()

               income    loan_amount       term  credit_history
default
0        20145.947902  608378.091172  28.376266        0.693198
1        21375.388846  526856.735676  36.045837        0.392666

# Train-Test Split

In [52]:
y = df.iloc[:,4]
X = df.iloc[:,0:4]

In [53]:
X.head()

   income  loan_amount  term  credit_history
0   14662       657144    30               1
1   17636       226200    54               1
2   17847       323619    24               0
3   20556       619547    42               1
4   17510       332159    60               1

In [54]:
y.head()

0    0
1    1
2    0
3    1
4    1
Name: default, dtype: int64

In [55]:
# 80% of the code is used for training, the remaining 20% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [56]:
# Standardize with StandardScaler()
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Risk Model Building

In [57]:
# Use a logistic regression to classify the data
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Model Performance

In [61]:
print(confusion_matrix(y_test, y_pred))

[[ 71  71]
 [ 20 238]]

In [62]:
print(accuracy_score(y_test, y_pred))

0.7725